### ISSUE TITLE
Main title should be changed and link to help.ubuntu.com

### ISSUE THREAD

**Issue by pmatulis** [canonical-web-and-design/docs.ubuntu.com#16]
I am concerned about the main title on [docs.ubuntu.com](http://docs.ubuntu.com):

**Ubuntu documentation**

This can cause confusion since official Ubuntu documentation is already hosted on [help.ubuntu.com](http://help.ubuntu.com).

d.u.c is like:

"Canonical Ubuntu documentation"
"Canonical Cloud documentation"
"Canonical-sponsored documentation"

It should also include a link to h.u.c : 

"For official Ubuntu documentation, go to [help.ubuntu.com](http://help.ubuntu.com)."

**Comment by pmatulis** [comment]
The motd file that spits out links upon user login (on every Ubuntu system) should be updated.

/etc/update-motd.d/10-help-text

```
#!/bin/sh
#
#    10-help-text - print the help text associated with the distro
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>,
#             Brian Murray <brian@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

printf "\n"
printf " * Documentation:  https://help.ubuntu.com\n"
printf " * Management:     https://landscape.canonical.com\n"
printf " * Support:        https://ubuntu.com/advantage\n"

**Comment by nottrobin** [comment]
As discussed in IRC:

- We should change the title
- We should link to help.ubuntu.com
- Consider changing domain name to docs.canonical.com or something similar

**Comment by nottrobin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Decide what to do with docs.ubuntu.com domain](https://trello.com/c/4ouNGtqy/2215-decide-what-to-do-with-docs-ubuntu-com-domain)

**Comment by caldav** [comment]
@pmatulis myself and the rest of the Marketing team were toying with the docs.developer.ubuntu.com domain name. I agree that the current solution, especially the title, could bring confusion to end users.

@nottrobin I have a "card not found" on the above ^

**Comment by nottrobin** [comment]
@caldav yeah that looks to our trello board. It adds those links automatically

**Comment by pmatulis** [comment]
@caldav I find [docs.developer.ubuntu.com](docs.developer.ubuntu.com) awkward.

Suggestions:

- [devdocs.ubuntu.com](devdocs.ubuntu.com)
- [cloud-docs.ubuntu.com](cloud-docs.ubuntu.com)
- [canonical-docs.ubuntu.com](canonical-docs.ubuntu.com)
- [docs.canonical.com](docs.canonical.com)

Recall that Landscape, which is, by and large, a private project will be linked from this domain. So using a ubuntu.com TLD may not be appropriate.

**Comment by anthonydillon** [comment]
I was under the impression that the docs site would be hosted at
docs.ubuntu.com.

If there is concern that this domain could be perceived as a location
dedicated to the desktop OS. Then I believe being creative with the
subdomain will not levitate this concern. I believe we could continue to
use docs.ubuntu.com. With a link to help.ubuntu.com at the top of the site.

Sorry if I have missed something. What are your thoughts?

**Comment by pmatulis** [comment]
The problem is that docs.ubuntu.com is a very general sounding domain name that suggests that it is for  documentation for the Ubuntu project as a whole, which it is not. I suppose we can rejig things so that it does do that, in addition to the Canonical-led stuff. Note that help.ubuntu.com hosts documentation for the Desktop *and* Server. Also the main thrust of that site is that it contains all official Ubuntu documentation, no matter the type.

**Comment by nottrobin** [comment]
I've been considering this for a while, and I think on balance I'm with @anthonydillon on the domain.

I think the whole point is for `docs.ubuntu.com` to be a general-sounding domain. It's meant to signify that it's a single platform for all documentation - ubuntu core, snapcraft, maas, landscape, vanilla-framework, documentation-builder itself, and hopefully eventually ubuntu API docs etc. etc..

I did initially appreciate the argument that `docs.ubuntu.com` makes it sound like it's exclusively documentation for Ubuntu, but I don't think there are any better alternatives. `docs.developer.ubuntu.com` is too long, and makes it sound like it's exclusively docs for `developer.ubuntu.com` (which it isn't) and in any case has the same "ubuntu.com" problem, and `docs.canonical.com` is just too corporate. Hosting core documentation on a `canonical.com` domain would send entirely the wrong message. In any case, a whole host of different content sits under `ubuntu.com` - both the site itself and its various subdomains.

I do accept that there might be some products that aren't at all comfortable sitting under `ubuntu.com` (this may apply to Snapcraft for example, as it's meant to be a cross-distro tool). But in that case I'd rather develop the ability for `docs.ubuntu.com` to have other domains pointed at it, so that Snapcraft docs could be at `docs.snapcraft.io`, but I still think the central domain for the service should be `docs.ubuntu.com`.

I do however wholeheartedly agree that the content of the `docs.ubuntu.com/` homepage should be changed to clarify the difference between the roles of this `docs.ubuntu.com` platform and `help.ubuntu.com` (though I'm not yet 100% clear on exactly what those differences are).

@pmahnke do you have any thoughts?

**Comment by pmahnke** [comment]
Moving the site will resolve nothing.  There are going to be two sites pointing to documentation.  We need to make sure it is clear for anyone to find all the docs that we do have.  I would propose to:

1. change the text of the docs.u.c site to not add the confusion (e.g. change 'The home of Ubuntu documentation.')
2. include links to the server and desktop help.u.c docs in the list of docs in 'Featured documentation'
3. perhaps include links to other docs as well, like LXD, conjure-up, etc.

I would also like to talk to the community team about making the docs tools available to them to use as well.

**Comment by pmahnke** [comment]
Closing this as we have fixed most of the issues.
