### ISSUE TITLE
TOC wraps incorrectly based on browser size

### ISSUE THREAD

**Issue by cjohnston1158** [canonical-web-and-design/docs.ubuntu.com#188]
## Summary

When viewing a page in full screen on my Macbook, the TOC will sometimes wrap to the bottom left. If I zoom out, it will appear correctly.

<img width="1344" alt="screen shot 2019-01-18 at 2 48 08 pm" src="https://user-images.githubusercontent.com/24707086/51549498-08122a00-1e17-11e9-93b5-467d7098147f.png">
<img width="774" alt="screen shot 2019-01-18 at 2 48 22 pm" src="https://user-images.githubusercontent.com/24707086/51549499-08122a00-1e17-11e9-84d6-c2a64c248ba1.png">

**Comment by matthewpaulthomas** [comment]
I reported the same problem with docs.jujucharms.com in [juju/docs#3301](https://github.com/juju/docs/issues/3301).

@tbille explained to me that if you don’t specify a template to documentation-builder, it uses [a default template](https://github.com/canonical-webteam/documentation-builder/blob/master/ubuntudesign/documentation_builder/resources/template.html). Since the same problem is occurring on multiple sites, the problem is probably there.

**Comment by pmahnke** [comment]
@matthewpaulthomas juju docs are now on discourse, so that's no longer relevant.

@cjohnston1158 it seems that the landscape docs on the landscape.canonical.com site have been updated that this set of docs is no longer current.  @roadmr can you confirm?  also why?

If that is true, we should repoint and redirect the old landscape docs to the new ones.

**Comment by cjohnston1158** [comment]
As far as I'm aware https://docs.ubuntu.com/landscape/en/ is the main set of docs for Landscape.

**Comment by SirSamTumless** [comment]
Thanks for flagging! We have added updating https://docs.ubuntu.com/landscape/en/ as a potential roadmap item for 21.08.
