### ISSUE TITLE
Style guide docs: confusing to have first-level headings on the left and second-level headings on the right, with no semantic relation whatsoever

### ISSUE THREAD

**Issue by fitojb** [canonical-web-and-design/docs.ubuntu.com#286]
What it says on the tin. The page could list its headings in a single navigation list, instead of splitting them in two, leaving the right-hand ToC with a list of H2’s that don’t make sense lumped together, because they belong to different H1 sections, but this is not reflected there.

Vanilla updated its navigation component a while ago to implement a left-side list that can display this missing relation among topics with indentation, so the right-side ToC can be dropped.

**Comment by nottrobin** [comment]
Thanks @fitojb. This is a valid point.

However the documentation system in question is legacy and we are working to migrate documentation off it, and the new documentation platforms don't have the same layout. So I'm afraid I don't think we're ever going to get to this particular issue, rather it will be fixed in due course when we migrate these docs elsewhere.

Closing this now.

**Comment by fitojb** [comment]
Sure, thanks!
